# Generated by Django 5.2.17 on 2026-09-21 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibida'), ('PENDING_EQUIPMENT', 'Pdte. llegada de equipos'), ('EQUIPMENT_OK', 'Equipos OK'), ('IN_INSTALLATION', 'En instalación'), ('COMPLETED', 'Completada')], default='RECEIVED', max_length=32, verbose_name='estado')),
                ('received_date', models.DateField(verbose_name='fecha de recepción')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='fecha programada')),
                ('installation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='inicio de instalación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('installation_address', models.CharField(blank=True, max_length=255, verbose_name='dirección de instalación')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('assigned_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='catalog.technician', verbose_name='técnico asignado')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commercial_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='comercial')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='customers.customer', verbose_name='cliente')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='catalog.worktype', verbose_name='tipo de trabajo')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-received_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Creación'), ('UPDATED', 'Actualización'), ('STATUS_CHANGED', 'Cambio de estado'), ('SCHEDULED', 'Programación'), ('RESCHEDULED', 'Reprogramación'), ('TECHNICIAN_CHANGED', 'Cambio de técnico'), ('INSTALLATION_STARTED', 'Inicio de instalación'), ('COMPLETED', 'Finalización')], max_length=32, verbose_name='tipo de evento')),
                ('description', models.TextField(verbose_name='descripción')),
                ('previous_value', models.TextField(blank=True, verbose_name='valor anterior')),
                ('new_value', models.TextField(blank=True, verbose_name='valor nuevo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workorders.workorder', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'Historial de orden',
                'verbose_name_plural': 'Historial de órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad solicitada')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_items', to='catalog.product', verbose_name='producto')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.workorder', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'Ítem de orden de trabajo',
                'verbose_name_plural': 'Ítems de órdenes de trabajo',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='workorders__status_2e2089_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['received_date'], name='workorders__receive_06e7da_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['scheduled_date'], name='workorders__schedul_202498_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='workorderitem_requested_quantity_positive'),
        ),
    ]
