# Generated by Django 5.2.17 on 2026-09-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-received_date', '-id'], 'permissions': [('schedule_workorder', 'Puede programar órdenes de trabajo')], 'verbose_name': 'Orden de trabajo', 'verbose_name_plural': 'Órdenes de trabajo'},
        ),
    ]
