# Generated by Django 5.2.17 on 2026-10-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_alter_workorder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Recibida'), ('PENDING_EQUIPMENT', 'Pendiente por pedido con proveedor'), ('EQUIPMENT_OK', 'Equipos completos para instalación'), ('IN_INSTALLATION', 'En instalación'), ('COMPLETED', 'Completada')], default='RECEIVED', max_length=32, verbose_name='estado'),
        ),
    ]
