# Generated by Django 5.2.17 on 2026-09-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='código de cliente')),
                ('code_system', models.CharField(blank=True, choices=[('CENTURION', 'Centurión'), ('ARION', 'Arion')], max_length=20, null=True, verbose_name='sistema de código')),
                ('trade_name', models.CharField(max_length=150, verbose_name='nombre comercial')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='razón social')),
                ('document', models.CharField(blank=True, max_length=30, verbose_name='documento o NIT')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['trade_name'],
                'constraints': [models.UniqueConstraint(fields=('code_system', 'customer_code'), name='unique_customer_code_per_system')],
            },
        ),
    ]
