# Generated by Django 5.2.17 on 2026-10-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_code_per_system',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='código de cliente'),
        ),
    ]
