# Generated by Django 5.2.17 on 2026-09-22 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('output_date', models.DateField(verbose_name='fecha de salida')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_warehouse_outputs', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_outputs', to='catalog.technician', verbose_name='técnico')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_output', to='workorders.workorder', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'Salida de almacén',
                'verbose_name_plural': 'Salidas de almacén',
                'ordering': ['-output_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseOutputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad entregada')),
                ('returned_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cantidad devuelta')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_output_items', to='catalog.product', verbose_name='producto')),
                ('warehouse_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehouseoutput', verbose_name='salida de almacén')),
                ('work_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_output_items', to='workorders.workorderitem', verbose_name='ítem de orden de trabajo')),
            ],
            options={
                'verbose_name': 'Ítem de salida de almacén',
                'verbose_name_plural': 'Ítems de salidas de almacén',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('delivered_quantity__gt', 0)), name='warehouseoutputitem_delivered_quantity_positive'), models.CheckConstraint(condition=models.Q(('returned_quantity__gte', 0)), name='warehouseoutputitem_returned_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('returned_quantity__lte', models.F('delivered_quantity'))), name='warehouseoutputitem_returned_quantity_lte_delivered')],
            },
        ),
    ]
