# Generated by Django 5.2.17 on 2026-09-25 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseoutput',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de conciliación'),
        ),
        migrations.AddField(
            model_name='warehouseoutput',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciled_warehouse_outputs', to=settings.AUTH_USER_MODEL, verbose_name='conciliado por'),
        ),
    ]
