ADMIN_WAREHOUSE_GROUP = "Administrador / Almacén"
COMMERCIAL_GROUP = "Comercial"
TECHNICAL_MANAGER_GROUP = "Jefe Técnica"
MANAGEMENT_GROUP = "Gerencia"

DEFAULT_GROUPS = (
    ADMIN_WAREHOUSE_GROUP,
    COMMERCIAL_GROUP,
    TECHNICAL_MANAGER_GROUP,
    MANAGEMENT_GROUP,
)
