# Generated by Django 5.2.17 on 2026-09-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='referencia')),
                ('product_type', models.CharField(choices=[('EQUIPMENT', 'Equipo'), ('MATERIAL', 'Material')], max_length=20, verbose_name='tipo de producto')),
                ('unit', models.CharField(choices=[('UNIT', 'Unidad'), ('METER', 'Metro'), ('ROLL', 'Rollo'), ('BOX', 'Caja')], max_length=20, verbose_name='unidad')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='apellido')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('technician_type', models.CharField(choices=[('STAFF', 'Planta'), ('CONTRACTOR', 'Contratista')], max_length=20, verbose_name='tipo de técnico')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de trabajo',
                'verbose_name_plural': 'Tipos de trabajo',
                'ordering': ['name'],
            },
        ),
    ]
