# Generated by Django 5.2.17 on 2026-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('INTRUSION', 'Intrusión'), ('CCTV', 'CCTV'), ('ELECTRIC_FENCE', 'Cercas eléctricas'), ('ACCESS_CONTROL', 'Control de acceso'), ('VEHICULAR', 'Línea vehicular'), ('MATERIALS_ACCESSORIES', 'Materiales y accesorios')], max_length=30, null=True, verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='código de producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=80, verbose_name='referencia / modelo'),
        ),
    ]
