# Generated by Django 5.2.17 on 2026-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_code_and_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('INTRUSION', 'Intrusión'), ('CCTV', 'CCTV'), ('ELECTRIC_FENCE', 'Cercas eléctricas'), ('ACCESS_CONTROL', 'Control de acceso'), ('VEHICULAR', 'Línea vehicular'), ('MATERIALS_ACCESSORIES', 'Materiales y accesorios')], max_length=30, verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='código de producto'),
        ),
    ]
